name: Build Electron App

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]

    steps:
      - name: Check out git repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Build application
        run: |
          if [ "${{ runner.os }}" == "Windows" ]; then
            npm run build -- --win --x64
          elif [ "${{ runner.os }}" == "macOS" ]; then
            npm run build -- --mac
          elif [ "${{ runner.os }}" == "Linux" ]; then
            npm run build -- --linux
          fi

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.os }}-build
          path: dist
